version: "3.9"
services:
  annotator:
    build: 
      context: . 
      dockerfile: Dockerfile.prod
    image: manikandan305/annotator
    ports:
      - "3000:3000"
    volumes:
      - /data/:/data/
    depends_on:
      - segmenter

  redis:
    image: "redis:alpine"

  segmenter:
    build: ./segmenter
    image: manikandan305/segmenter
    ports:
      - "8000:8000"
    volumes:
      - /data/:/data/
    depends_on:
      - redis
