version: "3.9"
services:
  annotator:
    build: 
      context: . 
      dockerfile: Dockerfile.prod
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"
    volumes:
      - /data/:/data/
    depends_on:
      - segmenter

  redis:
    image: "redis:alpine"

  segmenter:
    build: ./segmenter
    ports:
      - "8000:8000"
    volumes:
      - /data/:/data/
    depends_on:
      - redis
