version: "3.9"
services:
  annotator:
    build: 
      context: . 
      dockerfile: Dockerfile.dev
    image: annotator:dev
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - ./data/:/data/
      - ./:/audio-annotator/
    depends_on:
      - redis
      - db
  
  redis:
    image: "redis:alpine"

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=annotator_dev
    ports:
      - '5432:5432'