version: "3.9"
services:
  annotator:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - .:/audio-annotator/
      - sample:/data/

  redis:
    image: "redis:alpine"

  segmenter:
    build: ./segmenter
    ports:
      - "8000:8000"
    volumes:
      - .:/audio-annotator/
      - sample:/data/

  client:
    build: ./client
    port:
      - "1234:1234"
    volumes:
      - .:/audio-annotator/
      - sample:/data/
