FROM nikolaik/python-nodejs

RUN apt-get update && apt-get -y install libsndfile1
RUN python -m pip install --upgrade pip
RUN pip install librosa soundfile numpy fastapi uvicorn[standard] sqlalchemy
RUN pip install redis msgpack-numpy


WORKDIR /audio-annotator/server/
RUN npm i -g @nestjs/cli
RUN npm install 

WORKDIR /audio-annotator/client/
RUN npm install 


