name: deploy

on:
  push:
    branches: [master]

  workflow_dispatch:

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: Migrate DB Schema to Prod
      #   run: bash ./bin/deploy.sh

      # - name: Docker Login
      #   uses: docker/login-action@v2.0.0
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Docker build and push
      #   run: |
      #     docker buildx build --platform linux/arm64/v8 -t manikandan305/annotator -f ./Dockerfile.prod --no-cache --push .
      #     docker buildx build --platform linux/arm64/v8 -t manikandan305/segmenter --no-cache --push ./segmenter

      - name: "Wait for SSH"
        run: |
          while ! nc -w5 -z ${{secrets.VM_SSH_IP}} 22; do
                  sleep 5
                  echo "SSH not available..."
          done; echo "SSH ready!"

      - name: Copy docker-compose
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_SSH_IP }}
          username: ${{ secrets.VM_SSH_USER }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          source: "./docker-compose.yml"
          target: "/tmp/"

      - name: "Restart Containers"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_SSH_IP }}
          username: ${{ secrets.VM_SSH_USER }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            sudo rm -f /home/docker-compose.yml
            sudo mv /tmp/docker-compose.yml /home/
            cd /home
            sudo echo DATABASE_URL=${{ env.DATABASE_URL }} > /tmp/.annotator_env
            sudo mv /tmp/.annotator_env .
            sudo docker-compose down
            sudo docker-compose rm -f manikandan305/annotator manikandan305/segmenter
            sudo docker image rm -f manikandan305/annotator manikandan305/segmenter
            sudo DATABASE_URL=${{ env.DATABASE_URL }} docker-compose up -d --force-recreate annotator segmenter
